### ISSUE TITLE
Feature request: Enable compilation testing for PRs via travis

### ISSUE THREAD

**Issue by jmcnamara** [dpdk-org/dpdk#4]
This is mainly a test of the sandbox.

[Travis CI](https://travis-ci.com/) allows continuous integration testing of GitHub repos.

Once configured it runs designated tests on all submitted Pull Requests.

I'll submit a travis.yml config file in a PR.

**Comment by john-mcnamara-intel** [comment]
@pktgen,

You will need to enable automatic sync/building in the Travis config:

1. Log into [Travis CI](https://travis-ci.com/) using your GitHub account.
2. If dpdk-org isn't in you "Organisations" then add it.
3. Go to "DPDK Community (Sandbox)" and enable the "dpdk-org/dpdk" repository by flicking the switch.

It would probably be best to do that before merging the travis.yml config file since the merge will kick off an automatic build if the Travis configuration is done first.

John

**Comment by pktgen** [comment]
I think I have it enabled, please check.

**Comment by john-mcnamara-intel** [comment]
Looks good. If you merge the PR we can see if it kicks off the build sucessfully.

**Comment by pktgen** [comment]
How do I verify it was kicked off after the PR

**Comment by john-mcnamara-intel** [comment]
The build should show up [here](https://travis-ci.org/dpdk-org/dpdk) but it doesn't look like it has.

Looking at my view of the dpdk-org organisation it still looks turned off, although I don't know if that is just my view since I don't have Travis admin right on the org:

![travis](https://cloud.githubusercontent.com/assets/12168946/7883974/7ec6d266-0612-11e5-9359-84f3b2000b81.png)

**Comment by pktgen** [comment]
You have owners rights now.

**Comment by john-mcnamara-intel** [comment]
It is enable now and [working on a build](https://travis-ci.org/dpdk-org/dpdk/builds/64581480).

**Comment by john-mcnamara-intel** [comment]
The build is [complete and passing](https://travis-ci.org/dpdk-org/dpdk).

From now on any PRs that are submitted will be tested automatically prior to merge. End users will be notified if the build fails.

No further action is required.

I omitted running the unit tests for now since the default Travis VM doesn't have hugepages enabled. We could run a large subset of the unit tests with `--no-huge` but the test runner doesn't currently return non-zero for failing tests so that would have to be fixed first. I'll leave that for another PR.

**Comment by pktgen** [comment]
Cool, very nice

**Comment by SimonKagstrom** [comment]
I posted a patch to the DPDK mailing list a while ago to run in no-root mode without huge pages, although I guess the Travis VM can run as root anyway.

Nice addition anyhow!

**Comment by john-mcnamara-intel** [comment]
Hi Simon,

Thanks for that, I remember seeing your patch. I'll go back and look at it again.

For the record, the unit test app has to be patched as well to get it to use `--no-huge`. Here is [an earlier commit that does that](https://github.com/john-mcnamara-intel/dpdk/commit/5ed91b477e3093bead189ba1fb0bd29b2520e353). However, some of the tests will still fail (the multi-process ones I think).

So, all in all, probably not worth the effort until DPDK standardises on a test architecture.

Regards,

John
